Creation-page-formation
WildCodeSchool/oxygen-mvc pull request #31
Opened 2024-01-28 18:46 UTC by yazidsef

creation front-end page formation

2024-01-29 14:15 UTC, LaserHuy requested changes

2024-01-29 14:15 UTC, LaserHuy commented on src/Controller/FormationController.php
> +class HomeController extends AbstractController
HomeController to FormationController

2024-01-29 14:15 UTC, LaserHuy commented on src/View/formation/index.html.twig
> +{% extends '../layout.html.twig' %}
delete ../

2024-01-31 13:04 UTC, Benja-san commented on src/View/formation/index.html.twig
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.4.0/remixicon.css" crossorigin="">
this link is already imported in layout remove it and import parent content inside your stylesheet block

2024-01-31 13:04 UTC, Benja-san commented on src/View/formation/index.html.twig
> +                <h2>&quot; formation PHP developer &quot;</h2>
H1 before H2

2024-01-31 13:48 UTC, LaserHuy approved these changes
ok its good

2024-01-31 13:53 UTC, Benja-san requested changes

2024-01-31 13:53 UTC, Benja-san commented on database.sql
> +INSERT INTO `Discipline` (`id`, 'icon', 'name', 'description') VALUES
you don't need to insert id values since it is in auto increment as a primary key

2024-01-31 13:53 UTC, Benja-san commented on src/View/formation/index.html.twig
change H3 into h2 then

2024-01-31 14:37 UTC, Benja-san requested changes
databse changes haven't been done

2024-02-01 08:27 UTC, Benja-san approved these changes

2024-02-01 08:35 UTC, merged