securisation done for contact form
WildCodeSchool/oxygen-mvc pull request #65
Opened 2024-02-07 14:34 UTC by assma8jaballah

2024-02-07 14:44 UTC, LaserHuy approved these changes
Its ok!

2024-02-07 16:17 UTC, Benja-san requested changes

2024-02-07 16:17 UTC, Benja-san commented on database.sql
> +INSERT INTO `item` (`id`, `title`)
remove item table since it's useless

2024-02-08 09:57 UTC, Benja-san approved these changes

2024-02-08 09:57 UTC, merged